### PR TITLE
Use the same family for local as for remote address

### LINKED ISSUE #27: Fix IPv6 / IPv4 dichotomy
When creating the `ComposerClient` it binds to `localhost` which may resolve to either IPv6 or v4 address. Then, when it tries to send data to the server and the server address is not the same IP version, it fails.

We want to bind the client to whatever address will work with the given server address.

### PR DESCRIPTION
**Pull request by goodhoko**
To construct a socket it must be first bound to a local address and only then it can connect to a remote address.

For the connection to succeed both addresses must be of the same family (IPv4 or 6).

When constructing the client first parse the given server address to determine its family and then bind to a wildcard address of the same family.

fixes #27

### CODE REVIEW

File: crates/composer_api/src/lib.rs [hunk 1]
```diff
@@ -34,4 +34,37 @@ impl Client {
...
+            .ok_or(eyre!("can't resolve server address"))?;
+
+        // Set the address and port to 0 to let the OS choose unoccupied values for us
+        if server_address.is_ipv4() {
+            Ok("0.0.0.0:0")
+        } else if server_address.is_ipv6() {
+            Ok(":::0")
+        } else {
+            Err(eyre!("not an IP address"))
+        }
```
Comment (strohel) [inline crates/composer_api/src/lib.rs]: Supernit: we could avoid the `else` and `Err` by using `match` on the `server_address` instead.

**Review by strohel — COMMENTED** [review]
LGTM, one supernit.

BTW I was curious and looked up how we resolve this in our code. Turns out we use `socket2` (it exposes more OS features), which has separate `new()` that lets you specify address family you want. (not suggesting we should use it here)

**Review by strohel — APPROVED** [review]

File: crates/composer_api/src/lib.rs (hunk 1 above)
Comment (goodhoko) [reply crates/composer_api/src/lib.rs]: 💡aha! Not sure why I didn't notice that `SocketAddr` is an enum!

Changed in b76c74212e2ca69ef70472f266fe011b039acb01

**Review by strohel — APPROVED** [review]
